version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000

#    volumes:
#      - ./:/usr/src/app:ro


  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=mostafa
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=new-york-city-api
    ports:
      - "5435:5435"
#    volumes:
#      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
